services:
  postgres:
    image: postgres:15
    container_name: bd_snowflake_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./DDL.sql:/docker-entrypoint-initdb.d/01_DDL.sql
      - ./mock_data.sql:/docker-entrypoint-initdb.d/02_mock_data.sql
      - ./DML.sql:/docker-entrypoint-initdb.d/03_DML.sql
      - ./analysis.sql:/docker-entrypoint-initdb.d/04_analysis.sql
      - ./исходные данные:/docker-entrypoint-initdb.d/data

volumes:
  postgres_data:
